### ISSUE TITLE
please let me know how to deploy your application on local. 

### ISSUE THREAD

**Issue by JafferWilson** [zeshanb/multiplechoice#1]
I am trying to run the code using `ionic serve` but it is not working. Can you suggest how to deploy your application?

**Comment by PortalGuy** [comment]
how do I run this project ?

**Comment by zeshanb** [comment]
HI there,

1. After downloading MultipleChoiceQuiz repo
2. Download Chrome Web Server: [Chrome Web Server]( https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb)
3. Extract and click "choose folder" from Chrome Web Server
4. Click on the generated localhost url or visit the default url: http://127.0.0.1:8887
     Please unblock port 8887 in your local firewall or firewall bundled with your anti virus software.

As mentioned in readme, this app uses static JSON for data references and only needs a web server to serve the static content for web users.

Thank you,
Zeshan
